const politicalParties = [
  { "code": "3RD", "name": "3rd" },
  { "code": "A", "name": "ALL" },
  { "code": "ABO", "name": "ABOLITIONIST" },
  { "code": "AC", "name": "ANARCHIST" },
  { "code": "ACO", "name": "ANARCHO-COMMUNIST" },
  { "code": "ACP", "name": "ANARCHO CAPITALIST" },
  { "code": "ACR", "name": "ALL CROOKS" },
  { "code": "AD", "name": "ADARIAN" },
  { "code": "ADEM", "name": "AMERICAN DEMOCRAT" },
  { "code": "AE", "name": "AMERICAN EAGLE" },
  { "code": "AF", "name": "AMERICAN FIRST PARTY" },
  { "code": "AFP", "name": "AMERICAN FREEDOM PARTY" },
  { "code": "AG", "name": "ALMIGHTY GOD'S" },
  { "code": "AH", "name": "AMERICAN HERITAGE" },
  { "code": "AI", "name": "AMERICAN INDEPENDENT" },
  { "code": "AIP", "name": "AIP" },
  { "code": "AL", "name": "AMERICAN LABOR" },
  { "code": "AMA", "name": "AMERICA" },
  { "code": "ALL", "name": "ALLAH" },
  { "code": "AM", "name": "AMERICAN" },
  { "code": "AMC", "name": "AMERICAN CHRISTIAN" },
  { "code": "AMD", "name": "AMERICAN DELTA" },
  { "code": "AME", "name": "AMERICA'S" },
  { "code": "AMF", "name": "AMERICA FIRST" },
  { "code": "AMI", "name": "AMERICAN INDIAN" },
  { "code": "AMRE", "name": "American Reform" },
  { "code": "AMRL", "name": "AMERICAL LIBERTY" },
  { "code": "AN", "name": "AMERICAN NAZI" },
  { "code": "ANA", "name": "ANARCHY" },
  { "code": "ANL", "name": "ANIMAL LIFE" },
  { "code": "ANO", "name": "ANONYMOUS" },
  { "code": "ANP", "name": "AIN'T NO PARTY LIKE A POLITICAL PARTY" },
  { "code": "ANY", "name": "ANY" },
  { "code": "AO", "name": "ANTI OBAMA" },
  { "code": "AP", "name": "AMERICAN PATRIOT" },
  { "code": "APJ", "name": "APPLE JUICE" },
  { "code": "APP", "name": "AMERICA'S PARTY PENNSYLVANIA" },
  { "code": "APR", "name": "AMERICAN FIRST PROGRESSIVE" },
  { "code": "APTY", "name": "AMERICA's PARTY " },
  { "code": "AR", "name": "AMBIVALENT RIGHT" },
  { "code": "ARI", "name": "ARISTOCRAT" },
  { "code": "ARP", "name": "AMERICAN REVOLUTIONARY PARTY" },
  { "code": "ASF", "name": "AMERICA - SEMPER FI" },
  { "code": "ASI", "name": "ASIAN" },
  { "code": "ASM", "name": "ASSEMBLY" },
  { "code": "ASP", "name": "American Solidarity Party" },
  { "code": "AT", "name": "ATHEIST" },
  { "code": "ATP", "name": "AMERICAN TEA PARTY" },
  { "code": "AU", "name": "AMERICAN UNITY" },
  { "code": "AW", "name": "AWAKE" },
  { "code": "AZ", "name": "AQUAZIAN ZIONIST" },
  { "code": "AZPA", "name": "AQUARIAN ZIONIST PARTY OF AMERICA" },
  { "code": "AYE", "name": "Aseyev" },
  { "code": "B", "name": "BIRTHDAY" },
  { "code": "BA", "name": "BLUE ARMY" },
  { "code": "BH", "name": "BOTH" },
  { "code": "BL", "name": "BLISS" },
  { "code": "BLP", "name": "BLACK PANTHER" },
  { "code": "BM", "name": "BULL MOOSE" },
  { "code": "BMP", "name": "BOTH MAJOR PARTIES" },
  { "code": "BO", "name": "BARACK OBAMA" },
  { "code": "BP", "name": "BI-PARTISAN" },
  { "code": "BPAT", "name": "BEST PERSON AT THE TIME" },
  { "code": "BPFJ", "name": "BEST PERSON FOR THE JOB" },
  { "code": "BS", "name": "BERNIE SANDERS" },
  { "code": "BSRR", "name": "BEER/SEX/ROCK ROLL" },
  { "code": "BSTP", "name": "BEST PERSON" },
  { "code": "BTH", "name": "BOTH 1/2" },
  { "code": "BTM", "name": "BETWEEN MIDDLE" },
  { "code": "C", "name": "CONSERVATIVE" },
  { "code": "CA", "name": "CAPITALIST" },
  { "code": "CB", "name": "CAMPBELL PARTY" },
  { "code": "CC", "name": "CHRISTIAN CONSERVATIVE" },
  { "code": "CCO", "name": "CHRISTIAN COALITION" },
  { "code": "CCUS", "name": "CATHOLIC CENTER PARTY USA" },
  { "code": "CD", "name": "CHRISTIAN DEMOCRAT" },
  { "code": "CDU", "name": "CHRISTIAN DEMOCRATIC PARTY U.S.A." },
  { "code": "CDUN", "name": "CHRISTIAN DEMOCRAT UNION" },
  { "code": "CE", "name": "CENTRALIST" },
  { "code": "CF", "name": "CONFEDERATE" },
  { "code": "CFED", "name": "Constitutional Federalist" },
  { "code": "CH", "name": "CHRISTIAN" },
  { "code": "CHA", "name": "Chablais" },
  { "code": "CHG", "name": "CHANGE" },
  { "code": "CHY", "name": "Christianity" },
  { "code": "CI", "name": "COMMUNIST INDEPENDENT" },
  { "code": "CL", "name": "CONSTITUTIONAL" },
  { "code": "CLI", "name": "CHARLIE" },
  { "code": "CLL", "name": "CHRISTIANS FOR LIFE AND LIBERTY" },
  { "code": "CM", "name": "COMMUNIST" },
  { "code": "CMR", "name": "COMMERCIAL" },
  { "code": "CN", "name": "CONFIDENSIAL" },
  { "code": "CNC", "name": "CONSTITUTIONAL CONSERVATIVE" },
  { "code": "CNT", "name": "CENTRIST" },
  { "code": "CNLB", "name": "CENTRIST LIBERTARIAN" },
  { "code": "CO", "name": "CONSUMER'S" },
  { "code": "COD", "name": "CONSERVATIVE DEMOCRAT" },
  { "code": "COI", "name": "CONSERVATIVE INDEPENDENT" },
  { "code": "COL", "name": "COLL" },
  { "code": "COM", "name": "COMMUNIST PARTY USA" },
  { "code": "CON", "name": "CONSUMER" },
  { "code": "CP", "name": "CITIZEN'S" },
  { "code": "CPU", "name": "CPUSA" },
  { "code": "CR", "name": "Conservative Republican" },
  { "code": "CRE", "name": "CARE" },
  { "code": "CRT", "name": "CIVIL RIGHTS" },
  { "code": "CS", "name": "Common Sense" },
  { "code": "CSI", "name": "COMMON SENSE INDEPENDENT" },
  { "code": "CSIP", "name": "CSI PARTY" },
  { "code": "CT", "name": "CONSTITUTION" },
  { "code": "CTL", "name": "Cocktail Party" },
  { "code": "CTT", "name": "CONSTITUTIONALIST" },
  { "code": "D", "name": "DEMOCRATIC" },
  { "code": "DEAB", "name": "Democrats Abroad" },
  { "code": "DEC", "name": "DECEPTICON" },
  { "code": "DEM", "name": "_DEMOCRACY" },
  { "code": "DEP", "name": "DEPPERT" },
  { "code": "DIE", "name": "DIETZIST" },
  { "code": "DIS", "name": "DISABILITY" },
  { "code": "DKY", "name": "DONT KNOW YET" },
  { "code": "DL", "name": "DEMOCRATIC LIBERAL" },
  { "code": "DNA", "name": "Democratic-Non Affiliation" },
  { "code": "DNV", "name": "DO NOT VOTE" },
  { "code": "DPD", "name": "DEPENDED" },
  { "code": "DPN", "name": "DEPENDS" },
  { "code": "DPP", "name": "DEMOCRATIC PROGRESSIVE PARTY" },
  { "code": "DR", "name": "Democratic Republican" },
  { "code": "DS", "name": "DEMOCRATIC SOCIALIST" },
  { "code": "DSN", "name": "DEAD SOON" },
  { "code": "DSNY", "name": "Disney Party" },
  { "code": "DST", "name": "DMCRT SOCIALIST" },
  { "code": "DT", "name": "DON’T KNOW" },
  { "code": "DTP", "name": "DIESEL TRUCK PARTY" },
  { "code": "DTS", "name": "DECLINE TO STATE" },
  { "code": "E", "name": "EVERYDAY" },
  { "code": "ECO", "name": "Ecomagen" },
  { "code": "ECS", "name": "Economic Statism" },
  { "code": "EGA", "name": "Egalitare" },
  { "code": "EMET", "name": "EMET" },
  { "code": "ENP", "name": "EGYPTIAN" },
  { "code": "EPTY", "name": "Ethan's Party" },
  { "code": "EQU", "name": "EQuAliST" },
  { "code": "EX", "name": "EXPERT" },
  { "code": "FA", "name": "FASCIST" },
  { "code": "FAC", "name": "FACIST" },
  { "code": "FAS", "name": "FASCIM" },
  { "code": "FD", "name": "FREEDOM" },
  { "code": "FE", "name": "FEDERALIST" },
  { "code": "FLT", "name": "Free\Libertè" },
  { "code": "FM", "name": "FEMINIST MAJORITY" },
  { "code": "FO", "name": "FUGIFINO" },
  { "code": "FP", "name": "FREAK POWER" },
  { "code": "FR", "name": "FREE" },
  { "code": "FRA", "name": "FREE AGENT" },
  { "code": "FRUSA", "name": "FREEDOM USA" },
  { "code": "FS", "name": "FREEDOM SELF" },
  { "code": "FT", "name": "FREETHINKER" },
  { "code": "FTP", "name": "FOR THE PEOPLE" },
  { "code": "FUT", "name": "FUCK TRUP" },
  { "code": "G", "name": "GOD" },
  { "code": "GA", "name": "GAY" },
  { "code": "GAD", "name": "GUNS AND DOPE" },
  { "code": "GD", "name": "GREEN DEMOCRAT" },
  { "code": "GDI", "name": "GDI" },
  { "code": "GE", "name": "GALACTIC EMPIRE" },
  { "code": "GG", "name": "GOLD GOOSE" },
  { "code": "GIM", "name": "GIANT METEOR" },
  { "code": "GJ", "name": "GARY JOHNSON" },
  { "code": "GM", "name": "GRAND METACOSMOS" },
  { "code": "GN", "name": "GOOD NEIGHBOR" },
  { "code": "GO", "name": "GOOD ONE" },
  { "code": "GOP", "name": "GOP" },
  { "code": "GP", "name": "GREEN PARTY" },
  { "code": "GPUS", "name": "GREEN PARTY OF THE US" },
  { "code": "GR", "name": "GREEN" },
  { "code": "GRD", "name": "GREEN DEMOCRATIC" },
  { "code": "GRNI", "name": "GREEN INDEPENDENT" },
  { "code": "GRR", "name": "GRASS ROOT" },
  { "code": "GS", "name": "GO STEELERS" },
  { "code": "GT", "name": "Go Trump" },
  { "code": "GTP", "name": "GREEN TEA PARTY" },
  { "code": "GW", "name": "George Washington" },
  { "code": "H", "name": "HALLOWEEN" },
  { "code": "HAB", "name": "HABIBI" },
  { "code": "HAP", "name": "HAPPY" },
  { "code": "HC", "name": "HILLERY CLINTON" },
  { "code": "HE", "name": "HELLO" },
  { "code": "HI", "name": "HUMAN INTEREST" },
  { "code": "HIL", "name": "HILLARY" },
  { "code": "HILA", "name": "HILARY" },
  { "code": "HO", "name": "HORDE" },
  { "code": "HOG", "name": "HOG4BOSS" },
  { "code": "HP", "name": "Hoffman Party" },
  { "code": "HR", "name": "HUMAN RACE" },
  { "code": "HSP", "name": "HOLY SPIRIT" },
  { "code": "HTL", "name": "HITLER" },
  { "code": "HUM", "name": "HUMANITARIAN" },
  { "code": "HUP", "name": "HUMANE" },
  { "code": "I", "name": "INDEPENDENT" },
  { "code": "IA", "name": "INDEPENDENCE PARTY OF AMERICA" },
  { "code": "IAPP", "name": "INDEPENDENT AMERICAN PARTY OF PA" },
  { "code": "IC", "name": "INDEPENDENT-COMPLETION" },
  { "code": "ICC", "name": "Independent Constitutional Conservative" },
  { "code": "ICL", "name": "INDEPENDENT CONSERVATIVE LIBERTARIAN" },
  { "code": "ICO", "name": "INDEPENDENT CONSERVATIVE" },
  { "code": "ICON", "name": "INDEPENDENT CONSTITUTIONALIST" },
  { "code": "ID", "name": "INDEPENDENT DEMOCRAT" },
  { "code": "INDd", "name": "IND." },
  { "code": "INT", "name": "INTRA" },
  { "code": "INTE", "name": "INTELLIGENT" },
  { "code": "IDK", "name": "I DON'T KNOW" },
  { "code": "IDL", "name": "IDOL" },
  { "code": "IDR", "name": "I DONT REGISTER " },
  { "code": "IG", "name": "INDEPENDENT GREEN" },
  { "code": "IITM", "name": "I'M IN THE MIDDLE" },
  { "code": "IK", "name": "IDK" },
  { "code": "IL", "name": "INDEPENDENT/LIBERTARIAN" },
  { "code": "ILM", "name": "ILLUMINATI" },
  { "code": "IM", "name": "INDEPENDENT MODERATE" },
  { "code": "IN", "name": "INTERESTING" },
  { "code": "IND", "name": "INDEPENDENCE" },
  { "code": "INDE", "name": "INDEPENDANT" },
  { "code": "INDY", "name": "INDY" },
  { "code": "INRE", "name": "INDEPENDANT/REPUBLIC" },
  { "code": "INNA", "name": "Independent No Affiliation " },
  { "code": "INNP", "name": "INDEPENDENT/NO PARTY" },
  { "code": "IP", "name": "INDEPENDENT POPULIST" },
  { "code": "IPPA", "name": "IPPA" },
  { "code": "IR", "name": "INDEPENDENT REPUBLICAN" },
  { "code": "IS", "name": "INTERNATIONAL SOCIALIST" },
  { "code": "IT", "name": "INDEPENT" },
  { "code": "ITENT", "name": "INDEPENTENT" },
  { "code": "ITM", "name": "Intermediated" },
  { "code": "IV", "name": "INDIVIDUAL" },
  { "code": "IVFABP", "name": "I VOTE FOR A BETTER PERSON NOT" },
  { "code": "JBN", "name": "JACOBIN" },
  { "code": "J", "name": "JUBILEEIAN" },
  { "code": "JD", "name": "JEDI" },
  { "code": "JO", "name": "JACKASS-ONE" },
  { "code": "JON", "name": "JOHNSON'S" },
  { "code": "JP", "name": "JUSTICE PARTY" },
  { "code": "JS", "name": "JESUS" },
  { "code": "K", "name": "KLINGON" },
  { "code": "KEG", "name": "KEG" },
  { "code": "KN", "name": "KNOW NOTHING" },
  { "code": "KNP", "name": "KUNNERMAN" },
  { "code": "KOG", "name": "KINGDOM OF GOD" },
  { "code": "KQ", "name": "KINGS & QUEENS" },
  { "code": "KWAD", "name": "KWAD" },
  { "code": "L", "name": "LABOR" },
  { "code": "LA", "name": "LABORER" },
  { "code": "LAN", "name": "LANNISTER" },
  { "code": "LAT", "name": "LATINA" },
  { "code": "LD", "name": "Liberal Democrat" },
  { "code": "LEG", "name": "LEGALIST" },
  { "code": "LF", "name": "LAISSE-FAIRE CAPITALIST" },
  { "code": "LG", "name": "LIBERAL GREENE" },
  { "code": "LI", "name": "LIBERAL" },
  { "code": "LIB", "name": "Liberalist" },
  { "code": "LIBIN", "name": "LIBERAL/INDEPENDENT" },
  { "code": "LIUP", "name": "Liberty Union Party" },
  { "code": "LMNP", "name": "LEGAL MARIJAUNA NOW PARTY" },
  { "code": "LN", "name": "LIBERTARIAN" },
  { "code": "LNS", "name": "LIBERTARIAN SOCIALIST" },
  { "code": "LNSG", "name": "LIBERTARIAN NATIONAL SOCIALIST GREEN" },
  { "code": "LR", "name": "LIBERTARIAN REPUBLICAN" },
  { "code": "LREP", "name": "LIBERAL REPUBLICAN" },
  { "code": "LT", "name": "LIBERTARIAN TRANSHUMANIST" },
  { "code": "LUK", "name": "LUKAWANDA" },
  { "code": "M", "name": "MODERATE" },
  { "code": "MA", "name": "MAITER" },
  { "code": "MAJA", "name": "MARIJUANA" },
  { "code": "MAN", "name": "MAN" },
  { "code": "MARR", "name": "Marriage" },
  { "code": "MAY", "name": "MAYBE" },
  { "code": "MAS", "name": "MIGHT AS WELL" },
  { "code": "MC", "name": "McCain" },
  { "code": "MCHAR", "name": "MORAL CHARACTER" },
  { "code": "MDWP", "name": "MODERATE WARD PARTY" },
  { "code": "MG", "name": "MIDDLE GROUND" },
  { "code": "MI", "name": "MANAYUNK INDEPENDENT" },
  { "code": "MID", "name": "MIDDLE" },
  { "code": "MIG", "name": "MARK IS GOD" },
  { "code": "MIN", "name": "MODERATE \ INDEPENDENT" },
  { "code": "ML", "name": "MODERATE-LIBERAL" },
  { "code": "MM", "name": "MICKEY MOUSE" },
  { "code": "MMI", "name": "ME MYSELF AND I" },
  { "code": "MNT", "name": "MONARCHIST" },
  { "code": "MODR", "name": "MODERN REPUBLICAN" },
  { "code": "MP", "name": "Moderate Republican" },
  { "code": "MOP", "name": "Movement for a People's Party Or None" },
  { "code": "MRP", "name": "Marijuana Reform Party" },
  { "code": "MRT", "name": "MR TRUMP" },
  { "code": "MSE", "name": "MEASE" },
  { "code": "MU", "name": "MUTUAL" },
  { "code": "MUS", "name": "MUSLIM" },
  { "code": "MW", "name": "MODERN WHIG" },
  { "code": "MWP", "name": "MODERN WHIG PARTY" },
  { "code": "MX", "name": "MARXIST PARTY" },
  { "code": "MYMED", "name": "MEN YOGA MEDITATION" },
  { "code": "MYP", "name": "My Party" },
  { "code": "MZ", "name": "MADI Z" },
  { "code": "N", "name": "N/A" },
  { "code": "NA", "name": "NEW ALLIANCE" },
  { "code": "NAI", "name": "NEW AFRIKAN INDEPENDENCE" },
  { "code": "NAT", "name": "NAT'L TAXPAYER" },
  { "code": "NC", "name": "NON-COMMITTAL" },
  { "code": "NCP", "name": "NON-CONFORMIST PARTY" },
  { "code": "ND", "name": "NOT DEMO-REPO" },
  { "code": "NE", "name": "NEUTRAL" },
  { "code": "NEI", "name": "Not Either" },
  { "code": "NEO", "name": "NEO-AGRARIAN" },
  { "code": "NF", "name": "NO AFFILIATION" },
  { "code": "NI", "name": "NOT INTERESTED" },
  { "code": "NINC", "name": "NON-INCRIMINATING" },
  { "code": "NL", "name": "NATURAL LAW" },
  { "code": "NO", "name": "NO PARTY" },
  { "code": "NOA", "name": "NON-AFFILIATED" },
  { "code": "NODE", "name": "NON DENOMINATIONAL" },
  { "code": "NON", "name": "NONE" },
  { "code": "NOYO", "name": "None-Your" },
  { "code": "NOO", "name": "NO" },
  { "code": "NOP", "name": "NON-PARTISAN" },
  { "code": "NOPA", "name": "NO PARTY AFFILIATION" },
  { "code": "NOS", "name": "Non Specific" },
  { "code": "NOT", "name": "NOTALITARIAN" },
  { "code": "NOV", "name": "NOVELIST" },
  { "code": "NOW", "name": "NO WAY" },
  { "code": "NP", "name": "NEW PATRIOT" },
  { "code": "NPA", "name": "Non Party" },
  { "code": "NPF", "name": "No Preference" },
  { "code": "NPP", "name": "NEW PATRIOT PARTY" },
  { "code": "NPRO", "name": "NEW PROGRESSIVE" },
  { "code": "NPS", "name": "NPS" },
  { "code": "NRA", "name": "NRA" },
  { "code": "NS", "name": "NATIONAL SOCIALIST" },
  { "code": "NSAL", "name": "NSALP" },
  { "code": "NSSLP", "name": "THE NATIONAL SOCIALIST SONS OF LIBERTY PARTY" },
  { "code": "NST", "name": "NATIONALIST" },
  { "code": "NT", "name": "NATIONAL TAXPAYERS" },
  { "code": "NTRP", "name": "NOT TRUMP" },
  { "code": "NTS", "name": "NOT SURE" },
  { "code": "NU", "name": "NO LONGER IN USE" },
  { "code": "NVTR", "name": "#NeverTrump" },
  { "code": "NW", "name": "NEOWHIG" },
  { "code": "NZ", "name": "NAZI" },
  { "code": "NYP", "name": "NOT YOU PROBLEM" },
  { "code": "O", "name": "OPRAH" },
  { "code": "OBA", "name": "OBAMA" },
  { "code": "OLAP", "name": "Ol' American Party" },
  { "code": "OP", "name": "OPEN" },
  { "code": "OPV", "name": "OTHER POLITICAL VIEWS" },
  { "code": "OR", "name": "ORANGE" },
  { "code": "OTH", "name": "OTHER" },
  { "code": "OW", "name": "OLD WHIG" },
  { "code": "OWN", "name": "OWN" },
  { "code": "OWW", "name": "Old wagon Wheel" },
  { "code": "P", "name": "PUMPKIN" },
  { "code": "P2", "name": "PP" },
  { "code": "PA", "name": "PA FOR PEROT" },
  { "code": "PA2", "name": "PA" },
  { "code": "PAL", "name": "Pacifist/Libertarian" },
  { "code": "PAP", "name": "PEACE & PROSPERITY" },
  { "code": "PAR", "name": "PARTY FOR SOCIALISM AND LIBERIA" },
  { "code": "PART", "name": "PARTY" },
  { "code": "PAS", "name": "PENNSYLVANIA SOVEREIGNS" },
  { "code": "PAST", "name": "PASTAFARIEN" },
  { "code": "PE", "name": "PEDESTRIAN" },
  { "code": "PENN", "name": "PENNSYLVANIA" },
  { "code": "PEPA", "name": "PEACE PARTY" },
  { "code": "PER", "name": "PERSONAL" },
  { "code": "PF", "name": "PEACE AND FREEDOM" },
  { "code": "PFP", "name": "#66 PA FOR PEROT" },
  { "code": "PG", "name": "PACIFIC GREEN" },
  { "code": "PH", "name": "PROHIBITION" },
  { "code": "PHA", "name": "PHILOSOPHICAL ANARCHIST" },
  { "code": "PI", "name": "PENNSYLVANIA INDEPENDENT PARTY" },
  { "code": "PIR", "name": "PIRATE" },
  { "code": "PIZ", "name": "PIZZA PARTY" },
  { "code": "PJ", "name": "THE PARTY OF JAY" },
  { "code": "PL", "name": "PRO-LIFE" },
  { "code": "PLL", "name": "Pleasant Living" },
  { "code": "PNP", "name": "Pennsylvania Nationalist Party " },
  { "code": "PNT", "name": "PANTS PARTY" },
  { "code": "PNTS", "name": "PREFER NOT TO SAY" },
  { "code": "PO", "name": "POPULIST" },
  { "code": "POL", "name": "POLITICAL" },
  { "code": "POLA", "name": "POLITICAL ATHEIST" },
  { "code": "POO", "name": "PARTY OF ONE" },
  { "code": "PP", "name": "PATRIOT" },
  { "code": "PPD", "name": "PPD" },
  { "code": "PPOA", "name": "Progressive Party of America" },
  { "code": "PPP", "name": "PANSEXUAL PEACE PARTY" },
  { "code": "PPUS", "name": "PIRATE PARTY OF THE UNITED STATES" },
  { "code": "PR", "name": "PROGRESSIVE" },
  { "code": "PRE", "name": "PRESIDENT" },
  { "code": "PRI", "name": "PRIVIT" },
  { "code": "PRK", "name": "PHREAK THE 4TH" },
  { "code": "PRM", "name": "PRAGMATIST" },
  { "code": "PRO", "name": "PRO-FOR THE CULTURE" },
  { "code": "PRT", "name": "PEROT" },
  { "code": "PS", "name": "PACIFIST SOCIALIST" },
  { "code": "PSL", "name": "PSL" },
  { "code": "PSS", "name": "PIRATE STARSHIP" },
  { "code": "PUPA", "name": "PURGE PARTY" },
  { "code": "PT", "name": "PROUT" },
  { "code": "PU", "name": "PURITAN" },
  { "code": "PUE", "name": "Puerto Rico" },
  { "code": "PUR", "name": "PURPLE PARTY" },
  { "code": "PVT", "name": "Private" },
  { "code": "PZ", "name": "PRINCIPALITY OF ZION" },
  { "code": "R", "name": "REPUBLICAN" },
  { "code": "RA", "name": "RAINBOW" },
  { "code": "RAM", "name": "Rambler" },
  { "code": "RC", "name": "RATIONAL CITIZEN" },
  { "code": "RD", "name": "REFORMED" },
  { "code": "RDNA", "name": "REPUBLICAN DEMOCRATIC NO AFFILIATION" },
  { "code": "RE", "name": "REAL" },
  { "code": "REP", "name": "REPRESENTATIVE" },
  { "code": "RES", "name": "RESTRICTED" },
  { "code": "RF", "name": "REFORM" },
  { "code": "RGN", "name": "REAGANITE" },
  { "code": "RL", "name": "RIGHT TO LIFE" },
  { "code": "RO", "name": "ROYALIST" },
  { "code": "RON", "name": "RON PAUL" },
  { "code": "ROY", "name": "ROYAL" },
  { "code": "RP", "name": "REPRESENTITIVENESS" },
  { "code": "RPDM", "name": "REPUBLICAN DEMOCRATIC" },
  { "code": "RTV", "name": "RIGHT TO VOTE" },
  { "code": "RVA", "name": "REVOLUTIONARY ANARCHIST" },
  { "code": "RW", "name": "RIGHT WING" },
  { "code": "S", "name": "SOCIALIST" },
  { "code": "SA", "name": "SOCIAL ANARCHIST" },
  { "code": "SAME", "name": "SAME" },
  { "code": "SCIW", "name": "SHARE COMMON INTERESTS WITHIN" },
  { "code": "SD", "name": "SOCIALIST DEMOCRAT" },
  { "code": "SE", "name": "Self" },
  { "code": "SST", "name": "SECESSIONIST" },
  { "code": "SEC", "name": "SECREST PARTY" },
  { "code": "SECR", "name": "SECRETO" },
  { "code": "SEQ", "name": "Socialist Equality" },
  { "code": "SFC", "name": "SIR FRED THE CAT" },
  { "code": "SH", "name": "SKYHOOK" },
  { "code": "SI", "name": "SLOTH AND INDOLENCE" },
  { "code": "SIN", "name": "SINGLE" },
  { "code": "SIS", "name": "SISTER PARTY" },
  { "code": "SL", "name": "SOCIALIST LABOR" },
  { "code": "SM", "name": "SMUCK" },
  { "code": "SOA", "name": "SOCIALIST ALTERNATIVE" },
  { "code": "SOD", "name": "SOCIAL DEMOCRAT" },
  { "code": "SP", "name": "SOCIALIST PROGRESSIVE" },
  { "code": "SPA", "name": "spaghetti" },
  { "code": "SPI", "name": "SPIRITUALISM" },
  { "code": "SPL", "name": "SPLIT PARTY" },
  { "code": "SPP", "name": "SILLY PARTY" },
  { "code": "SPS", "name": "SPUSA" },
  { "code": "SPU", "name": "SOCIALIST PARTY USA" },
  { "code": "SQ", "name": "S.Q.U.I.D." },
  { "code": "SR", "name": "SQUIRREL REFORM" },
  { "code": "SSU", "name": "SOVIET SOCIALIST UNION" },
  { "code": "SUP", "name": "THE SURPRISE PARTY" },
  { "code": "SV", "name": "SPLIT VOTE" },
  { "code": "SW", "name": "SOCIALIST WORKERS" },
  { "code": "SWP", "name": "SWP" },
  { "code": "T", "name": "TAXPAYERS" },
  { "code": "TB", "name": "TRUTH BASED" },
  { "code": "TFP", "name": "THE FUN PARTY" },
  { "code": "TH", "name": "THE HUMANITY PARTY" },
  { "code": "TGPU", "name": "THE GREEN PARTY OF THE UNITED" },
  { "code": "THP", "name": "TRANSHUMANIST PARTY" },
  { "code": "THPY", "name": "Third Party" },
  { "code": "THR", "name": "THREE PERCENTER PARTY" },
  { "code": "TNP", "name": "The New President" },
  { "code": "TO", "name": "TOGA" },
  { "code": "TP", "name": "Tea Party" },
  { "code": "TPC", "name": "Tea Party Conservative" },
  { "code": "TPP", "name": "Tea Party Patriot" },
  { "code": "TRP", "name": "TRUMP" },
  { "code": "TVP", "name": "TVP" },
  { "code": "TWSP", "name": "TAX WALL STREET PARTY" },
  { "code": "TWVP", "name": "TWELVE VISIONS PARTY" },
  { "code": "U", "name": "UNITARIAN" },
  { "code": "UAT", "name": "UNITED AMERICAN TAXPAYERS" },
  { "code": "UC", "name": "UNITED CONSTITUTION" },
  { "code": "UDC", "name": "UNDECLARED" },
  { "code": "UDCL", "name": "UNDISCLOSED" },
  { "code": "UK", "name": "UNITED KNOWLEDGE" },
  { "code": "UL", "name": "US LABOR" },
  { "code": "UA", "name": "UNITED AMERICA" },
  { "code": "UNA", "name": "UNAFFILIATED" },
  { "code": "UNC", "name": "UNCERTAIN" },
  { "code": "UND", "name": "UNDECIDED" },
  { "code": "UNDT", "name": "UNDETERMINED" },
  { "code": "UNER", "name": "UNENROLLED" },
  { "code": "UNK", "name": "UNKNOWN" },
  { "code": "UNPP", "name": "United Progressive Party" },
  { "code": "UNS", "name": "UNSURE" },
  { "code": "UP", "name": "UNITED PEOPLE'S" },
  { "code": "UPA", "name": "United Party of America" },
  { "code": "UPP", "name": "U.S. Pirate Party" },
  { "code": "US", "name": "U.S. SOCIALIST" },
  { "code": "USA", "name": "USA" },
  { "code": "USC", "name": "US CONSTITUTION" },
  { "code": "USM", "name": "USA MINUTEMEN" },
  { "code": "USMJ", "name": "USMJ PARTY" },
  { "code": "USP", "name": "UNITED STATES PIRATE" },
  { "code": "UT", "name": "US TAXPAYERS" },
  { "code": "UTP", "name": "Utopian" },
  { "code": "UU", "name": "U" },
  { "code": "UW", "name": "UWSA" },
  { "code": "UWS", "name": "UNITED WE STAND" },
  { "code": "V", "name": "VOTE" },
  { "code": "VFI", "name": "VOTE FOR WHO I LIKE @ THE TIME" },
  { "code": "VIG", "name": "VIGILANTE" },
  { "code": "VP", "name": "VETERAN'S PARTY OF AMERICA" },
  { "code": "WFP", "name": "WORKING FAMILIES PARTY" },
  { "code": "WH", "name": "WHIG" },
  { "code": "WHO", "name": "whoever" },
  { "code": "WR", "name": "WIG-REPUBLICAN" },
  { "code": "WI", "name": "WILD" },
  { "code": "WIC", "name": "WHOMEVER I CHOOSE" },
  { "code": "WIG", "name": "WIG" },
  { "code": "WIL", "name": "WHATEVER I LIKE" },
  { "code": "WIO", "name": "WHEN ITS OBAMA" },
  { "code": "WIS", "name": "WILL SEE" },
  { "code": "WITB", "name": "WHO I THINK IS BEST" },
  { "code": "WIW", "name": "WHOEVER I WANT" },
  { "code": "WJW", "name": "WHAT JESUS WANTS" },
  { "code": "WL", "name": "WHITE LOTUS" },
  { "code": "WN", "name": "White Nationalist" },
  { "code": "WOR", "name": "WORKERS WORLD" },
  { "code": "WP", "name": "WORKERS PARTY" },
  { "code": "WPP", "name": "WORKING PEOPLE'S" },
  { "code": "WWP", "name": "WORLD WORKERS PARTY" },
  { "code": "WS", "name": "Wynd Sok" },
  { "code": "WTBC", "name": "WHOEVER WILL BE THE BEST CANID" },
  { "code": "WTH", "name": "WILLING TO HELP" },
  { "code": "WUAB", "name": "WHOMEVER UNDER AUTHORITY OF THE BIBLE" },
  { "code": "X", "name": "X" },
  { "code": "YI", "name": "YOUTH INTERNATIONAL" },
  { "code": "YO", "name": "YOUNG OUTSIDER" },
  { "code": "YVIS", "name": "YOUR VOTE IS SECRET" },
];
